import { Lightbulb, ScanEye, Target } from "lucide-react"

type Guide = { simple: string; steps: string[]; tryIt: string; watch: string }

const guides: Record<string, Guide> = {
  array: { simple: "An array is a row of numbered boxes. Because every box has an index, you can jump straight to an item when you know its position.", steps: ["Choose values and place them in order.", "Use the index to read, update, insert, or remove a value.", "Notice that inserting in the middle shifts the values after it."], tryIt: "Insert a value near the start, then compare it with adding one at the end.", watch: "Index labels, highlighted cells, and any values shifting right or left." },
  stack: { simple: "A stack works like a stack of plates: you add to the top and remove from the top. The last value in is always the first one out.", steps: ["Push adds a value on top.", "Pop removes the current top value.", "Peek reads the top without removing it."], tryIt: "Push three values, then pop them one by one.", watch: "The top marker and how the order reverses as values leave." },
  queue: { simple: "A queue works like a line at a counter: the first value to arrive is the first value served.", steps: ["Enqueue adds a value at the rear.", "Dequeue removes the value at the front.", "The front and rear markers keep the order clear."], tryIt: "Add three values, then remove two.", watch: "The front and rear pointers, plus the order values exit." },
  "linked-list": { simple: "A linked list stores each value in its own node. Every node points to the next one, so the list can grow without needing one continuous block of memory.", steps: ["Create a node with a value and a next link.", "Reconnect links when inserting or deleting.", "Traverse by following next pointers from the head."], tryIt: "Insert a value in the middle, then remove it.", watch: "The head, tail, and arrows that are rewired during an operation." },
  "binary-tree": { simple: "A binary tree is a family structure where each node can have up to two children. In this visualizer, smaller values go left and larger values go right.", steps: ["Start at the root.", "Compare the new value with the current node.", "Move left or right until an empty position is found."], tryIt: "Insert values that make both left and right branches.", watch: "Each comparison and the path chosen from the root." },
  sorting: { simple: "Sorting puts values in an order so they are easier to scan and search. Each algorithm uses a different strategy to move values into place.", steps: ["Compare the highlighted values.", "Swap or copy them when the order is wrong.", "Repeat until every value is in its final position."], tryIt: "Run the same small list with Bubble Sort and Selection Sort.", watch: "Comparisons, swaps, and the portion already known to be sorted." },
  graph: { simple: "A graph is a set of points connected by lines. BFS explores layer by layer; DFS follows one path deeply before coming back.", steps: ["Pick a starting node.", "BFS keeps nearby nodes in a queue.", "DFS follows a branch, then backtracks when it reaches the end."], tryIt: "Run BFS and DFS from the same node.", watch: "Visited nodes, the queue or traversal path, and the final visit order." },
  heap: { simple: "A heap is a tree that keeps its most important value at the top. A max heap keeps the largest value there; a min heap keeps the smallest.", steps: ["Add a value at the next open position.", "Bubble it upward until the heap rule is true.", "After removing the root, move the last value down into place."], tryIt: "Insert a small value and then a very large value into a max heap.", watch: "Parent-child comparisons and the values swapping up or down." },
  "infix-postfix": { simple: "Infix is the normal way people write maths, such as A + B. Postfix puts the operator after its values, which lets a stack evaluate the expression without brackets.", steps: ["Read tokens from left to right.", "Send operands to the output immediately.", "Use the stack to hold operators until precedence says they can be output."], tryIt: "Convert A+B*C and see why multiplication comes first.", watch: "The operator stack, postfix output, and each precedence decision." },
  polynomial: { simple: "A polynomial is a collection of terms such as 2x² and 3x. Multiplication pairs every term in the first polynomial with every term in the second, then combines like powers.", steps: ["Select one term from each polynomial.", "Multiply coefficients and add exponents.", "Merge terms that have the same exponent."], tryIt: "Use (x + 1) and (x + 2), then follow each term pair.", watch: "The selected nodes and the result list as like terms combine." },
  huffman: { simple: "Huffman coding compresses text by giving short binary codes to common characters and longer codes to rare characters.", steps: ["Count each character's frequency.", "Repeatedly join the two least frequent nodes.", "Use left as 0 and right as 1 to read each final code."], tryIt: "Encode text with repeated letters, such as BANANA.", watch: "The priority queue, merged tree nodes, and final character codes." },
  dijkstra: { simple: "Dijkstra's algorithm finds the cheapest route from a start node when all edge weights are zero or positive.", steps: ["Set the start distance to zero and all others to infinity.", "Visit the unvisited node with the smallest known distance.", "Relax its edges: replace a neighbour's distance when a shorter route is found."], tryIt: "Load an example graph and change the start and end nodes.", watch: "Tentative distances, visited nodes, and the path that becomes final." },
  "message-queue": { simple: "A message queue lets one part of a system send work while another part processes it later. It keeps producers and consumers from needing to run at the same speed.", steps: ["A producer publishes a message.", "The queue holds it safely.", "A consumer takes and processes it."], tryIt: "Send several messages before starting the consumer.", watch: "Message state as it moves from producer, through the queue, to consumer." },
}

export function TopicExplanation({ topic }: { topic: string }) {
  const guide = guides[topic]
  if (!guide) return null
  return <section className="mb-6 rounded-2xl border border-violet-500/15 bg-violet-500/[0.04] p-5">
    <div className="flex gap-3"><Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-violet-500" /><div><h2 className="font-semibold">Start here: the plain-English version</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{guide.simple}</p></div></div>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><div><h3 className="flex items-center gap-2 text-sm font-semibold"><ScanEye className="h-4 w-4 text-violet-500" />How to follow the animation</h3><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm leading-6 text-muted-foreground">{guide.steps.map(step => <li key={step}>{step}</li>)}</ol></div><div className="space-y-4"><div><h3 className="flex items-center gap-2 text-sm font-semibold"><Target className="h-4 w-4 text-violet-500" />Try this</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{guide.tryIt}</p></div><div><h3 className="text-sm font-semibold">What to watch</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{guide.watch}</p></div></div></div>
  </section>
}
