// lib/battle/problems.ts
//
// Code Battle's problem bank. Every testCases entry was generated by
// actually running a reference implementation (not hand-computed) — see
// the generation script referenced in the PR/commit for this file if the
// numbers ever look suspicious.
//
// Deliberately scoped to problems with a single, unambiguous correct
// output (numbers, strings, booleans, or an array with one valid order)
// so the judge can do a plain deep-equality check — no partial credit,
// no "any valid answer" logic. That's a real constraint on which
// problems can go in this bank: e.g. a Two Sum here specifies "return
// indices in ascending order" precisely so it stays exact-match judgeable
// even though a hashmap solution could otherwise return either order.
//
// NEVER import this file into client code — testCases.*.expected is the
// answer key. Only server-side routes (create/submit) may touch it.

import type { BattleProblem } from "./types"

export const BATTLE_PROBLEMS: BattleProblem[] = [
  {
    slug: "reverse-string",
    title: "Reverse a String",
    difficulty: "Easy",
    topic: "String",
    description: "Given a string s, return the string reversed.",
    constraints: ["1 ≤ s.length ≤ 1000", "s consists of printable ASCII characters"],
    starterCode: "function solve(s) {\n  \n}",
    examples: [{ input: 's = "hello"', output: '"olleh"' }],
    testCases: [
      { input: ["hello"], expected: "olleh" },
      { input: ["algomaitri"], expected: "irtiamogla" },
      { input: ["a"], expected: "a" },
    ],
  },
  {
    slug: "find-maximum",
    title: "Find the Maximum",
    difficulty: "Easy",
    topic: "Array",
    description: "Given an array of integers nums, return the largest value in it.",
    constraints: ["1 ≤ nums.length ≤ 1000", "-10^4 ≤ nums[i] ≤ 10^4"],
    starterCode: "function solve(nums) {\n  \n}",
    examples: [{ input: "nums = [3,7,2,9,4]", output: "9" }],
    testCases: [
      { input: [[3, 7, 2, 9, 4]], expected: 9 },
      { input: [[-5, -1, -10]], expected: -1 },
      { input: [[42]], expected: 42 },
    ],
  },
  {
    slug: "valid-palindrome",
    title: "Valid Palindrome",
    difficulty: "Easy",
    topic: "String",
    description:
      "Given a string s consisting only of lowercase English letters, return true if it reads the same forwards and backwards, otherwise false.",
    constraints: ["1 ≤ s.length ≤ 1000", "s consists of lowercase English letters only"],
    starterCode: "function solve(s) {\n  \n}",
    examples: [{ input: 's = "racecar"', output: "true" }],
    testCases: [
      { input: ["racecar"], expected: true },
      { input: ["hello"], expected: false },
      { input: ["a"], expected: true },
    ],
  },
  {
    slug: "factorial",
    title: "Factorial",
    difficulty: "Easy",
    topic: "Recursion",
    description: "Given a non-negative integer n, return n! (n factorial).",
    constraints: ["0 ≤ n ≤ 12"],
    starterCode: "function solve(n) {\n  \n}",
    examples: [{ input: "n = 5", output: "120" }],
    testCases: [
      { input: [5], expected: 120 },
      { input: [0], expected: 1 },
      { input: [7], expected: 5040 },
    ],
  },
  {
    slug: "two-sum",
    title: "Two Sum",
    difficulty: "Medium",
    topic: "Hashing",
    description:
      "Given an array of integers nums and an integer target, return the indices of the two numbers that add up to target, as [i, j] with i < j. Exactly one valid pair exists for every input.",
    constraints: ["2 ≤ nums.length ≤ 1000", "Exactly one valid answer exists"],
    starterCode: "function solve(nums, target) {\n  \n}",
    examples: [{ input: "nums = [2,7,11,15], target = 9", output: "[0,1]" }],
    testCases: [
      { input: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { input: [[3, 2, 4], 6], expected: [1, 2] },
      { input: [[1, 5, 3, 8], 11], expected: [2, 3] },
    ],
  },
  {
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "Medium",
    topic: "Stack",
    description:
      "Given a string s containing just the characters ()[]{}, return true if every bracket is closed by the same type in the correct order.",
    constraints: ["1 ≤ s.length ≤ 1000"],
    starterCode: "function solve(s) {\n  \n}",
    examples: [{ input: 's = "()[]{}"', output: "true" }],
    testCases: [
      { input: ["()[]{}"], expected: true },
      { input: ["(]"], expected: false },
      { input: ["([{}])"], expected: true },
      { input: ["(("], expected: false },
    ],
  },
  {
    slug: "maximum-subarray",
    title: "Maximum Subarray",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    description:
      "Given an integer array nums, find the contiguous subarray with the largest sum and return that sum.",
    constraints: ["1 ≤ nums.length ≤ 1000", "-10^4 ≤ nums[i] ≤ 10^4"],
    starterCode: "function solve(nums) {\n  \n}",
    examples: [{ input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6" }],
    testCases: [
      { input: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 },
      { input: [[1]], expected: 1 },
      { input: [[5, 4, -1, 7, 8]], expected: 23 },
    ],
  },
  {
    slug: "merge-sorted-arrays",
    title: "Merge Two Sorted Arrays",
    difficulty: "Medium",
    topic: "Array",
    description:
      "Given two arrays a and b, each already sorted in ascending order, return a single sorted array containing all of their elements.",
    constraints: ["0 ≤ a.length, b.length ≤ 1000"],
    starterCode: "function solve(a, b) {\n  \n}",
    examples: [{ input: "a = [1,3,5], b = [2,4,6]", output: "[1,2,3,4,5,6]" }],
    testCases: [
      { input: [[1, 3, 5], [2, 4, 6]], expected: [1, 2, 3, 4, 5, 6] },
      { input: [[], [1, 2]], expected: [1, 2] },
      { input: [[1, 1, 1], [1, 1]], expected: [1, 1, 1, 1, 1] },
    ],
  },
  {
    slug: "longest-substring-no-repeat",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Hard",
    topic: "String",
    description:
      "Given a string s, return the length of the longest substring that contains no repeating characters.",
    constraints: ["0 ≤ s.length ≤ 1000"],
    starterCode: "function solve(s) {\n  \n}",
    examples: [{ input: 's = "abcabcbb"', output: "3" }],
    testCases: [
      { input: ["abcabcbb"], expected: 3 },
      { input: ["bbbbb"], expected: 1 },
      { input: ["pwwkew"], expected: 3 },
      { input: [""], expected: 0 },
    ],
  },
  {
    slug: "trapping-rain-water",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    topic: "Two Pointers",
    description:
      "Given an array height representing an elevation map where each bar has width 1, return how much water it can trap after raining.",
    constraints: ["1 ≤ height.length ≤ 1000", "0 ≤ height[i] ≤ 10^4"],
    starterCode: "function solve(height) {\n  \n}",
    examples: [{ input: "height = [0,1,0,2,1,0,1,3,2,1,2,1]", output: "6" }],
    testCases: [
      { input: [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], expected: 6 },
      { input: [[4, 2, 0, 3, 2, 5]], expected: 9 },
      { input: [[1, 1, 1]], expected: 0 },
    ],
  },
  {
    slug: "kth-largest-element",
    title: "Kth Largest Element",
    difficulty: "Hard",
    topic: "Sorting",
    description: "Given an integer array nums and an integer k, return the kth largest element (not the kth distinct).",
    constraints: ["1 ≤ k ≤ nums.length ≤ 1000"],
    starterCode: "function solve(nums, k) {\n  \n}",
    examples: [{ input: "nums = [3,2,1,5,6,4], k = 2", output: "5" }],
    testCases: [
      { input: [[3, 2, 1, 5, 6, 4], 2], expected: 5 },
      { input: [[3, 2, 3, 1, 2, 4, 5, 5, 6], 4], expected: 4 },
      { input: [[1], 1], expected: 1 },
    ],
  },
  {
    slug: "longest-common-subsequence",
    title: "Longest Common Subsequence",
    difficulty: "Hard",
    topic: "Dynamic Programming",
    description:
      "Given two strings a and b, return the length of their longest common subsequence (not necessarily contiguous).",
    constraints: ["0 ≤ a.length, b.length ≤ 200"],
    starterCode: "function solve(a, b) {\n  \n}",
    examples: [{ input: 'a = "abcde", b = "ace"', output: "3" }],
    testCases: [
      { input: ["abcde", "ace"], expected: 3 },
      { input: ["abc", "abc"], expected: 3 },
      { input: ["abc", "def"], expected: 0 },
    ],
  },
]

export function getBattleProblem(slug: string): BattleProblem | undefined {
  return BATTLE_PROBLEMS.find((p) => p.slug === slug)
}

/** Picks numQuestions problems matching the given filters, in random order. */
export function pickBattleQuestions(config: { difficulty: string; topics: string[] }, numQuestions: number): string[] {
  let pool = BATTLE_PROBLEMS
  if (config.difficulty !== "Mixed") {
    pool = pool.filter((p) => p.difficulty === config.difficulty)
  }
  if (config.topics.length > 0) {
    pool = pool.filter((p) => config.topics.includes(p.topic))
  }
  if (pool.length === 0) pool = BATTLE_PROBLEMS // filters matched nothing — fall back to the full bank rather than error

  const shuffled = [...pool].sort(() => Math.random() - 0.5)
  const picked: string[] = []
  for (let i = 0; i < numQuestions; i++) {
    picked.push(shuffled[i % shuffled.length].slug) // wrap around if numQuestions > pool size
  }
  return picked
}
